namespace Tellstick.Model
{
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;

    using Tellstick.Model.Enums;

    public class DefaultDataDbInitializer : DropCreateDatabaseIfModelChanges<TellstickDBContext>
    {
        private List<ActionType> TellstickActionTypes()
        {
            var tellstickActionTypes = new List<ActionType>
            {
                new ActionType { Active = true, Type = Enums.ActionType.TurnOn},
                new ActionType { Active = true, Type = Enums.ActionType.TurnOff},
                new ActionType { Active = true, Type = Enums.ActionType.TurnOff}
            };

            return tellstickActionTypes;
        }

        private List<Protocol> TellstickProtocols()
        {
            var tellstickProtocols = new List<Protocol>
            {
                new Protocol { Active = true, Type = Enums.Protocol.arctech },
                new Protocol { Active = true, Type = Enums.Protocol.brateck },
                new Protocol { Active = true, Type = Enums.Protocol.everflourish },
                new Protocol { Active = true, Type = Enums.Protocol.fuhaote },
                new Protocol { Active = true, Type = Enums.Protocol.hasta },
                new Protocol { Active = true, Type = Enums.Protocol.ikea },
                new Protocol { Active = true, Type = Enums.Protocol.kangtai },
                new Protocol { Active = true, Type = Enums.Protocol.risingsun },
                new Protocol { Active = true, Type = Enums.Protocol.sartano },
                new Protocol { Active = true, Type = Enums.Protocol.silvanchip },
                new Protocol { Active = true, Type = Enums.Protocol.upm },
                new Protocol { Active = true, Type = Enums.Protocol.waveman },
                new Protocol { Active = true, Type = Enums.Protocol.x10 },
                new Protocol { Active = true, Type = Enums.Protocol.yidong }
            };

            return tellstickProtocols;
        }

        private List<ModelTypeAndTellstickModel> TellstickModels()
        {
            var tellstickModels = new List<ModelTypeAndTellstickModel>
            {
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Anslut },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Anslut },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Anslut },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Anslut },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Anslut },

                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Brennenstuhl },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Brennenstuhl },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Brennenstuhl },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Brennenstuhl },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Brennenstuhl },

                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Chacon },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Chacon },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Chacon },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Chacon },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Chacon },

                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Hasta },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Hasta },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Hasta },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Hasta },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Hasta },

                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Intertechno },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Intertechno },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Intertechno },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Intertechno },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Intertechno },

                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Kappa },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Kappa },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Kappa },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Kappa },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Kappa },

                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Nexa },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Nexa },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Nexa },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Nexa },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Nexa },

                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Proove },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Proove },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Proove },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Proove },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Proove },

                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Rusta },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Rusta },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Rusta },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Rusta },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Rusta },

                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Sartano },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Sartano },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Sartano },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Sartano },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Sartano },

                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.codeswitch, Manufacturer = ModelManufacturer.Waveman },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.bell, Manufacturer = ModelManufacturer.Waveman },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearning, Manufacturer = ModelManufacturer.Waveman },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningDimmer, Manufacturer = ModelManufacturer.Waveman },
                new ModelTypeAndTellstickModel { Active = true, Type = Enums.ModelType.selflearningSwitch, Manufacturer = ModelManufacturer.Waveman }
            };

            return tellstickModels;
        }

        private List<Scheduler> TellstickSchedulers()
        {
            var tellstickSchedulers = new List<Scheduler>
            {
                new Scheduler { Active = true, CronDescription = "Triggar varje sekund", CronExpression = "0/1 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar varannan sekund", CronExpression = "0/2 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 3:e sekund", CronExpression = "0/3 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 4:e sekund", CronExpression = "0/4 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 5:e sekund", CronExpression = "0/5 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 6:e sekund", CronExpression = "0/6 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 7:e sekund", CronExpression = "0/7 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 8:e sekund", CronExpression = "0/8 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 9:e sekund", CronExpression = "0/9 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 10:e sekund", CronExpression = "0/10 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 20:e sekund", CronExpression = "0/30 * * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 30:e sekund", CronExpression = "0/30 * * * * ?"},

                new Scheduler { Active = true, CronDescription = "Triggar varje minut", CronExpression = "* * * * *"},
                new Scheduler { Active = true, CronDescription = "Triggar varannan minut", CronExpression = "0 0/2 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 3:e minut", CronExpression = "0 0/3 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 4:e minut", CronExpression = "0 0/4 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 5:e minut", CronExpression = "0 0/5 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 6:e minut", CronExpression = "0 0/6 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 7:e minut", CronExpression = "0 0/7 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 8:e minut", CronExpression = "0 0/8 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 9:e minut", CronExpression = "0 0/9 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 10:e minut", CronExpression = "0 0/10 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 15:e minut", CronExpression = "0 0/15 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 20:e minut", CronExpression = "0 0/20 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 25:e minut", CronExpression = "0 0/25 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 30:e minut", CronExpression = "0 0/30 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 35:e minut", CronExpression = "0 0/35 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 40:e minut", CronExpression = "0 0/40 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 45:e minut", CronExpression = "0 0/45 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 50:e minut", CronExpression = "0 0/50 * * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar var 55:e minut", CronExpression = "0 0/55 * * * ?"},

                new Scheduler { Active = true, CronDescription = "Triggar var 5:e minut, Måndag - Fredag", CronExpression = "*/5 * * * MON-FRI"},

                new Scheduler { Active = true, CronDescription = "Triggar kl 00:00 varje dag", CronExpression = "0 0 0 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 00:15 varje dag", CronExpression = "0 15 0 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 00:30 varje dag", CronExpression = "0 30 0 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 00:45 varje dag", CronExpression = "0 45 0 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 01:00 varje dag", CronExpression = "0 0 1 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 01:15 varje dag", CronExpression = "0 15 1 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 01:30 varje dag", CronExpression = "0 30 1 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 01:45 varje dag", CronExpression = "0 45 1 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 02:00 varje dag", CronExpression = "0 0 2 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 02:15 varje dag", CronExpression = "0 15 2 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 02:30 varje dag", CronExpression = "0 30 2 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 02:45 varje dag", CronExpression = "0 45 2 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 03:00 varje dag", CronExpression = "0 0 3 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 03:15 varje dag", CronExpression = "0 15 3 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 03:30 varje dag", CronExpression = "0 30 3 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 03:45 varje dag", CronExpression = "0 45 3 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 04:00 varje dag", CronExpression = "0 0 4 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 04:15 varje dag", CronExpression = "0 15 4 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 04:30 varje dag", CronExpression = "0 30 4 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 04:45 varje dag", CronExpression = "0 45 4 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 05:00 varje dag", CronExpression = "0 0 5 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 05:15 varje dag", CronExpression = "0 15 5 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 05:30 varje dag", CronExpression = "0 30 5 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 05:45 varje dag", CronExpression = "0 45 5 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 06:00 varje dag", CronExpression = "0 0 6 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 06:15 varje dag", CronExpression = "0 15 6 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 06:30 varje dag", CronExpression = "0 30 6 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 06:45 varje dag", CronExpression = "0 45 6 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 07:00 varje dag", CronExpression = "0 0 7 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 07:15 varje dag", CronExpression = "0 15 7 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 07:30 varje dag", CronExpression = "0 30 7 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 07:45 varje dag", CronExpression = "0 45 7 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 08:00 varje dag", CronExpression = "0 0 8 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 08:15 varje dag", CronExpression = "0 15 8 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 08:30 varje dag", CronExpression = "0 30 8 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 08:45 varje dag", CronExpression = "0 45 8 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 09:00 varje dag", CronExpression = "0 0 9 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 09:15 varje dag", CronExpression = "0 15 9 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 09:30 varje dag", CronExpression = "0 30 9 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 09:45 varje dag", CronExpression = "0 45 9 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 10:00 varje dag", CronExpression = "0 0 10 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 10:15 varje dag", CronExpression = "0 15 10 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 10:30 varje dag", CronExpression = "0 30 10 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 10:45 varje dag", CronExpression = "0 45 10 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 11:00 varje dag", CronExpression = "0 0 11 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 11:15 varje dag", CronExpression = "0 15 11 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 11:30 varje dag", CronExpression = "0 30 11 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 11:45 varje dag", CronExpression = "0 45 11 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 12:00 varje dag", CronExpression = "0 0 12 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 12:15 varje dag", CronExpression = "0 15 12 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 12:30 varje dag", CronExpression = "0 30 12 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 12:45 varje dag", CronExpression = "0 45 12 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 13:00 varje dag", CronExpression = "0 0 13 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 13:15 varje dag", CronExpression = "0 15 13 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 13:30 varje dag", CronExpression = "0 30 13 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 13:45 varje dag", CronExpression = "0 45 13 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 14:00 varje dag", CronExpression = "0 0 14 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 14:15 varje dag", CronExpression = "0 15 14 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 14:30 varje dag", CronExpression = "0 30 14 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 14:45 varje dag", CronExpression = "0 45 14 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 15:00 varje dag", CronExpression = "0 0 15 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 15:15 varje dag", CronExpression = "0 15 15 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 15:30 varje dag", CronExpression = "0 30 15 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 15:45 varje dag", CronExpression = "0 45 15 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 16:00 varje dag", CronExpression = "0 0 16 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 16:15 varje dag", CronExpression = "0 15 16 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 16:30 varje dag", CronExpression = "0 30 16 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 16:45 varje dag", CronExpression = "0 45 16 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 17:00 varje dag", CronExpression = "0 0 17 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 17:15 varje dag", CronExpression = "0 15 17 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 17:30 varje dag", CronExpression = "0 30 17 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 17:45 varje dag", CronExpression = "0 45 17 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 18:00 varje dag", CronExpression = "0 0 18 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 18:15 varje dag", CronExpression = "0 15 18 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 18:30 varje dag", CronExpression = "0 30 18 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 18:45 varje dag", CronExpression = "0 45 18 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 19:00 varje dag", CronExpression = "0 0 19 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 19:15 varje dag", CronExpression = "0 15 19 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 19:30 varje dag", CronExpression = "0 30 19 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 19:45 varje dag", CronExpression = "0 45 19 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 20:00 varje dag", CronExpression = "0 0 20 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 20:15 varje dag", CronExpression = "0 15 20 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 20:30 varje dag", CronExpression = "0 30 20 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 20:45 varje dag", CronExpression = "0 45 20 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 21:00 varje dag", CronExpression = "0 0 21 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 21:15 varje dag", CronExpression = "0 15 21 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 21:30 varje dag", CronExpression = "0 30 21 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 21:45 varje dag", CronExpression = "0 45 21 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 22:00 varje dag", CronExpression = "0 0 22 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 22:15 varje dag", CronExpression = "0 15 22 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 22:30 varje dag", CronExpression = "0 30 22 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 22:45 varje dag", CronExpression = "0 45 22 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 23:00 varje dag", CronExpression = "0 0 23 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 23:15 varje dag", CronExpression = "0 15 23 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 23:30 varje dag", CronExpression = "0 30 23 * * ?"},
                new Scheduler { Active = true, CronDescription = "Triggar kl 23:45 varje dag", CronExpression = "0 45 23 * * ?"}
            };

            return tellstickSchedulers;
        }

        private List<Parameter> TellstickParameters()
        {
            var tellstickParameters = new List<Parameter>
            {
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.A },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.B },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.C },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.D },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.E },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.F },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.G },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.H },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.I },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.J },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.K },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.L },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.M },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.N },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.O },
                new Parameter { Active = true, Unit = Parameter_Unit._1, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._2, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._3, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._4, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._5, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._6, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._7, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._8, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._9, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._10, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._11, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._12, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._13, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._14, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._15, House = Parameter_House.P },
                new Parameter { Active = true, Unit = Parameter_Unit._16, House = Parameter_House.P }
            };

            return tellstickParameters;
        }

        protected override void Seed(TellstickDBContext context)
        {
            context.ActionTypes.AddRange(this.TellstickActionTypes());

            context.Protocols.AddRange(this.TellstickProtocols());

            context.Models.AddRange(this.TellstickModels());

            context.Schedulers.AddRange(this.TellstickSchedulers());

            context.Parameters.AddRange(this.TellstickParameters());

            context.SaveChanges();
        }
    }
}