using Core.Model.Enums;

namespace Core.Model
{
    public partial class DefaultDataDbInitializer
    {
        private Country[] AllCountries()
        {
            var allCountries = new Country[]
            {
                new Country {Active = true, Name = "Afghanistan", Code = "93", ISOAlpha2 = "AF", ISOAlpha3 = "AFG"},
                new Country {Active = true, Name = "Albania", Code = "355", ISOAlpha2 = "AL", ISOAlpha3 = "ALB"},
                new Country {Active = true, Name = "Algeria", Code = "213", ISOAlpha2 = "DZ", ISOAlpha3 = "DZA"},
                new Country {Active = true, Name = "American Samoa", Code = "1-684", ISOAlpha2 = "AS", ISOAlpha3 = "ASM"},
                new Country {Active = true, Name = "Andorra", Code = "376", ISOAlpha2 = "AD", ISOAlpha3 = "AND"},
                new Country {Active = true, Name = "Angola", Code = "244", ISOAlpha2 = "AO", ISOAlpha3 = "AGO"},
                new Country {Active = true, Name = "Anguilla", Code = "1-264", ISOAlpha2 = "AI", ISOAlpha3 = "AIA"},
                new Country {Active = true, Name = "Antarctica", Code = "672", ISOAlpha2 = "AQ", ISOAlpha3 = "ATA"},
                new Country {Active = true, Name = "Antigua and Barbuda", Code = "1-268", ISOAlpha2 = "AG", ISOAlpha3 = "ATG"},
                new Country {Active = true, Name = "Argentina", Code = "54", ISOAlpha2 = "AR", ISOAlpha3 = "ARG"},
                new Country {Active = true, Name = "Armenia", Code = "374", ISOAlpha2 = "AM", ISOAlpha3 = "ARM"},
                new Country {Active = true, Name = "Aruba", Code = "297", ISOAlpha2 = "AW", ISOAlpha3 = "ABW"},
                new Country {Active = true, Name = "Australia", Code = "61", ISOAlpha2 = "AU", ISOAlpha3 = "AUS"},
                new Country {Active = true, Name = "Austria", Code = "43", ISOAlpha2 = "AT", ISOAlpha3 = "AUT"},
                new Country {Active = true, Name = "Azerbaijan", Code = "994", ISOAlpha2 = "AZ", ISOAlpha3 = "AZE"},
                new Country {Active = true, Name = "Bahamas", Code = "1-242", ISOAlpha2 = "BS", ISOAlpha3 = "BHS"},
                new Country {Active = true, Name = "Bahrain", Code = "973", ISOAlpha2 = "BH", ISOAlpha3 = "BHR"},
                new Country {Active = true, Name = "Bangladesh", Code = "880", ISOAlpha2 = "BD", ISOAlpha3 = "BGD"},
                new Country {Active = true, Name = "Barbados", Code = "1-246", ISOAlpha2 = "BB", ISOAlpha3 = "BRB"},
                new Country {Active = true, Name = "Belarus", Code = "375", ISOAlpha2 = "BY", ISOAlpha3 = "BLR"},
                new Country {Active = true, Name = "Belgium", Code = "32", ISOAlpha2 = "BE", ISOAlpha3 = "BEL"},
                new Country {Active = true, Name = "Belize", Code = "501", ISOAlpha2 = "BZ", ISOAlpha3 = "BLZ"},
                new Country {Active = true, Name = "Benin", Code = "229", ISOAlpha2 = "BJ", ISOAlpha3 = "BEN"},
                new Country {Active = true, Name = "Bermuda", Code = "1-441", ISOAlpha2 = "BM", ISOAlpha3 = "BMU"},
                new Country {Active = true, Name = "Bhutan", Code = "975", ISOAlpha2 = "BT", ISOAlpha3 = "BTN"},
                new Country {Active = true, Name = "Bolivia", Code = "591", ISOAlpha2 = "BO", ISOAlpha3 = "BOL"},
                new Country {Active = true, Name = "Bosnia and Herzegovina", Code = "387", ISOAlpha2 = "BA", ISOAlpha3 = "BIH"},
                new Country {Active = true, Name = "Botswana", Code = "267", ISOAlpha2 = "BW", ISOAlpha3 = "BWA"},
                new Country {Active = true, Name = "Brazil", Code = "55", ISOAlpha2 = "BR", ISOAlpha3 = "BRA"},
                new Country {Active = true, Name = "British Indian Ocean Territory", Code = "246", ISOAlpha2 = "IO", ISOAlpha3 = "IOT"},
                new Country {Active = true, Name = "British Virgin Islands", Code = "1-284", ISOAlpha2 = "VG", ISOAlpha3 = "VGB"},
                new Country {Active = true, Name = "Brunei", Code = "673", ISOAlpha2 = "BN", ISOAlpha3 = "BRN"},
                new Country {Active = true, Name = "Bulgaria", Code = "359", ISOAlpha2 = "BG", ISOAlpha3 = "BGR"},
                new Country {Active = true, Name = "Burkina Faso", Code = "226", ISOAlpha2 = "BF", ISOAlpha3 = "BFA"},
                new Country {Active = true, Name = "Burundi", Code = "257", ISOAlpha2 = "BI", ISOAlpha3 = "BDI"},
                new Country {Active = true, Name = "Cambodia", Code = "855", ISOAlpha2 = "KH", ISOAlpha3 = "KHM"},
                new Country {Active = true, Name = "Cameroon", Code = "237", ISOAlpha2 = "CM", ISOAlpha3 = "CMR"},
                new Country {Active = true, Name = "Canada", Code = "1", ISOAlpha2 = "CA", ISOAlpha3 = "CAN"},
                new Country {Active = true, Name = "Cape Verde", Code = "238", ISOAlpha2 = "CV", ISOAlpha3 = "CPV"},
                new Country {Active = true, Name = "Cayman Islands", Code = "1-345", ISOAlpha2 = "KY", ISOAlpha3 = "CYM"},
                new Country {Active = true, Name = "Central African Republic", Code = "236", ISOAlpha2 = "CF", ISOAlpha3 = "CAF"},
                new Country {Active = true, Name = "Chad", Code = "235", ISOAlpha2 = "TD", ISOAlpha3 = "TCD"},
                new Country {Active = true, Name = "Chile", Code = "56", ISOAlpha2 = "CL", ISOAlpha3 = "CHL"},
                new Country {Active = true, Name = "China", Code = "86", ISOAlpha2 = "CN", ISOAlpha3 = "CHN"},
                new Country {Active = true, Name = "Christmas Island", Code = "61", ISOAlpha2 = "CX", ISOAlpha3 = "CXR"},
                new Country {Active = true, Name = "Cocos Islands", Code = "61", ISOAlpha2 = "CC", ISOAlpha3 = "CCK"},
                new Country {Active = true, Name = "Colombia", Code = "57", ISOAlpha2 = "CO", ISOAlpha3 = "COL"},
                new Country {Active = true, Name = "Comoros", Code = "269", ISOAlpha2 = "KM", ISOAlpha3 = "COM"},
                new Country {Active = true, Name = "Cook Islands", Code = "682", ISOAlpha2 = "CK", ISOAlpha3 = "COK"},
                new Country {Active = true, Name = "Costa Rica", Code = "506", ISOAlpha2 = "CR", ISOAlpha3 = "CRI"},
                new Country {Active = true, Name = "Croatia", Code = "385", ISOAlpha2 = "HR", ISOAlpha3 = "HRV"},
                new Country {Active = true, Name = "Cuba", Code = "53", ISOAlpha2 = "CU", ISOAlpha3 = "CUB"},
                new Country {Active = true, Name = "Curacao", Code = "599", ISOAlpha2 = "CW", ISOAlpha3 = "CUW"},
                new Country {Active = true, Name = "Cyprus", Code = "357", ISOAlpha2 = "CY", ISOAlpha3 = "CYP"},
                new Country {Active = true, Name = "Czech Republic", Code = "420", ISOAlpha2 = "CZ", ISOAlpha3 = "CZE"},
                new Country {Active = true, Name = "Democratic Republic of the Congo", Code = "243", ISOAlpha2 = "CD", ISOAlpha3 = "COD"},
                new Country {Active = true, Name = "Denmark", Code = "45", ISOAlpha2 = "DK", ISOAlpha3 = "DNK"},
                new Country {Active = true, Name = "Djibouti", Code = "253", ISOAlpha2 = "DJ", ISOAlpha3 = "DJI"},
                new Country {Active = true, Name = "Dominica", Code = "1-767", ISOAlpha2 = "DM", ISOAlpha3 = "DMA"},
                new Country {Active = true, Name = "Dominican Republic", Code = "1-809, 1-829, 1-849", ISOAlpha2 = "DO", ISOAlpha3 = "DOM"},
                new Country {Active = true, Name = "East Timor", Code = "670", ISOAlpha2 = "TL", ISOAlpha3 = "TLS"},
                new Country {Active = true, Name = "Ecuador", Code = "593", ISOAlpha2 = "EC", ISOAlpha3 = "ECU"},
                new Country {Active = true, Name = "Egypt", Code = "20", ISOAlpha2 = "EG", ISOAlpha3 = "EGY"},
                new Country {Active = true, Name = "El Salvador", Code = "503", ISOAlpha2 = "SV", ISOAlpha3 = "SLV"},
                new Country {Active = true, Name = "Equatorial Guinea", Code = "240", ISOAlpha2 = "GQ", ISOAlpha3 = "GNQ"},
                new Country {Active = true, Name = "Eritrea", Code = "291", ISOAlpha2 = "ER", ISOAlpha3 = "ERI"},
                new Country {Active = true, Name = "Estonia", Code = "372", ISOAlpha2 = "EE", ISOAlpha3 = "EST"},
                new Country {Active = true, Name = "Ethiopia", Code = "251", ISOAlpha2 = "ET", ISOAlpha3 = "ETH"},
                new Country {Active = true, Name = "Falkland Islands", Code = "500", ISOAlpha2 = "FK", ISOAlpha3 = "FLK"},
                new Country {Active = true, Name = "Faroe Islands", Code = "298", ISOAlpha2 = "FO", ISOAlpha3 = "FRO"},
                new Country {Active = true, Name = "Fiji", Code = "679", ISOAlpha2 = "FJ", ISOAlpha3 = "FJI"},
                new Country {Active = true, Name = "Finland", Code = "358", ISOAlpha2 = "FI", ISOAlpha3 = "FIN"},
                new Country {Active = true, Name = "France", Code = "33", ISOAlpha2 = "FR", ISOAlpha3 = "FRA"},
                new Country {Active = true, Name = "French Polynesia", Code = "689", ISOAlpha2 = "PF", ISOAlpha3 = "PYF"},
                new Country {Active = true, Name = "Gabon", Code = "241", ISOAlpha2 = "GA", ISOAlpha3 = "GAB"},
                new Country {Active = true, Name = "Gambia", Code = "220", ISOAlpha2 = "GM", ISOAlpha3 = "GMB"},
                new Country {Active = true, Name = "Georgia", Code = "995", ISOAlpha2 = "GE", ISOAlpha3 = "GEO"},
                new Country {Active = true, Name = "Germany", Code = "49", ISOAlpha2 = "DE", ISOAlpha3 = "DEU"},
                new Country {Active = true, Name = "Ghana", Code = "233", ISOAlpha2 = "GH", ISOAlpha3 = "GHA"},
                new Country {Active = true, Name = "Gibraltar", Code = "350", ISOAlpha2 = "GI", ISOAlpha3 = "GIB"},
                new Country {Active = true, Name = "Greece", Code = "30", ISOAlpha2 = "GR", ISOAlpha3 = "GRC"},
                new Country {Active = true, Name = "Greenland", Code = "299", ISOAlpha2 = "GL", ISOAlpha3 = "GRL"},
                new Country {Active = true, Name = "Grenada", Code = "1-473", ISOAlpha2 = "GD", ISOAlpha3 = "GRD"},
                new Country {Active = true, Name = "Guam", Code = "1-671", ISOAlpha2 = "GU", ISOAlpha3 = "GUM"},
                new Country {Active = true, Name = "Guatemala", Code = "502", ISOAlpha2 = "GT", ISOAlpha3 = "GTM"},
                new Country {Active = true, Name = "Guernsey", Code = "44-1481", ISOAlpha2 = "GG", ISOAlpha3 = "GGY"},
                new Country {Active = true, Name = "Guinea", Code = "224", ISOAlpha2 = "GN", ISOAlpha3 = "GIN"},
                new Country {Active = true, Name = "Guinea-Bissau", Code = "245", ISOAlpha2 = "GW", ISOAlpha3 = "GNB"},
                new Country {Active = true, Name = "Guyana", Code = "592", ISOAlpha2 = "GY", ISOAlpha3 = "GUY"},
                new Country {Active = true, Name = "Haiti", Code = "509", ISOAlpha2 = "HT", ISOAlpha3 = "HTI"},
                new Country {Active = true, Name = "Honduras", Code = "504", ISOAlpha2 = "HN", ISOAlpha3 = "HND"},
                new Country {Active = true, Name = "Hong Kong", Code = "852", ISOAlpha2 = "HK", ISOAlpha3 = "HKG"},
                new Country {Active = true, Name = "Hungary", Code = "36", ISOAlpha2 = "HU", ISOAlpha3 = "HUN"},
                new Country {Active = true, Name = "Iceland", Code = "354", ISOAlpha2 = "IS", ISOAlpha3 = "ISL"},
                new Country {Active = true, Name = "India", Code = "91", ISOAlpha2 = "IN", ISOAlpha3 = "IND"},
                new Country {Active = true, Name = "Indonesia", Code = "62", ISOAlpha2 = "ID", ISOAlpha3 = "IDN"},
                new Country {Active = true, Name = "Iran", Code = "98", ISOAlpha2 = "IR", ISOAlpha3 = "IRN"},
                new Country {Active = true, Name = "Iraq", Code = "964", ISOAlpha2 = "IQ", ISOAlpha3 = "IRQ"},
                new Country {Active = true, Name = "Ireland", Code = "353", ISOAlpha2 = "IE", ISOAlpha3 = "IRL"},
                new Country {Active = true, Name = "Isle of Man", Code = "44-1624", ISOAlpha2 = "IM", ISOAlpha3 = "IMN"},
                new Country {Active = true, Name = "Israel", Code = "972", ISOAlpha2 = "IL", ISOAlpha3 = "ISR"},
                new Country {Active = true, Name = "Italy", Code = "39", ISOAlpha2 = "IT", ISOAlpha3 = "ITA"},
                new Country {Active = true, Name = "Ivory Coast", Code = "225", ISOAlpha2 = "CI", ISOAlpha3 = "CIV"},
                new Country {Active = true, Name = "Jamaica", Code = "1-876", ISOAlpha2 = "JM", ISOAlpha3 = "JAM"},
                new Country {Active = true, Name = "Japan", Code = "81", ISOAlpha2 = "JP", ISOAlpha3 = "JPN"},
                new Country {Active = true, Name = "Jersey", Code = "44-1534", ISOAlpha2 = "JE", ISOAlpha3 = "JEY"},
                new Country {Active = true, Name = "Jordan", Code = "962", ISOAlpha2 = "JO", ISOAlpha3 = "JOR"},
                new Country {Active = true, Name = "Kazakhstan", Code = "7", ISOAlpha2 = "KZ", ISOAlpha3 = "KAZ"},
                new Country {Active = true, Name = "Kenya", Code = "254", ISOAlpha2 = "KE", ISOAlpha3 = "KEN"},
                new Country {Active = true, Name = "Kiribati", Code = "686", ISOAlpha2 = "KI", ISOAlpha3 = "KIR"},
                new Country {Active = true, Name = "Kosovo", Code = "383", ISOAlpha2 = "XK", ISOAlpha3 = "XKX"},
                new Country {Active = true, Name = "Kuwait", Code = "965", ISOAlpha2 = "KW", ISOAlpha3 = "KWT"},
                new Country {Active = true, Name = "Kyrgyzstan", Code = "996", ISOAlpha2 = "KG", ISOAlpha3 = "KGZ"},
                new Country {Active = true, Name = "Laos", Code = "856", ISOAlpha2 = "LA", ISOAlpha3 = "LAO"},
                new Country {Active = true, Name = "Latvia", Code = "371", ISOAlpha2 = "LV", ISOAlpha3 = "LVA"},
                new Country {Active = true, Name = "Lebanon", Code = "961", ISOAlpha2 = "LB", ISOAlpha3 = "LBN"},
                new Country {Active = true, Name = "Lesotho", Code = "266", ISOAlpha2 = "LS", ISOAlpha3 = "LSO"},
                new Country {Active = true, Name = "Liberia", Code = "231", ISOAlpha2 = "LR", ISOAlpha3 = "LBR"},
                new Country {Active = true, Name = "Libya", Code = "218", ISOAlpha2 = "LY", ISOAlpha3 = "LBY"},
                new Country {Active = true, Name = "Liechtenstein", Code = "423", ISOAlpha2 = "LI", ISOAlpha3 = "LIE"},
                new Country {Active = true, Name = "Lithuania", Code = "370", ISOAlpha2 = "LT", ISOAlpha3 = "LTU"},
                new Country {Active = true, Name = "Luxembourg", Code = "352", ISOAlpha2 = "LU", ISOAlpha3 = "LUX"},
                new Country {Active = true, Name = "Macau", Code = "853", ISOAlpha2 = "MO", ISOAlpha3 = "MAC"},
                new Country {Active = true, Name = "Macedonia", Code = "389", ISOAlpha2 = "MK", ISOAlpha3 = "MKD"},
                new Country {Active = true, Name = "Madagascar", Code = "261", ISOAlpha2 = "MG", ISOAlpha3 = "MDG"},
                new Country {Active = true, Name = "Malawi", Code = "265", ISOAlpha2 = "MW", ISOAlpha3 = "MWI"},
                new Country {Active = true, Name = "Malaysia", Code = "60", ISOAlpha2 = "MY", ISOAlpha3 = "MYS"},
                new Country {Active = true, Name = "Maldives", Code = "960", ISOAlpha2 = "MV", ISOAlpha3 = "MDV"},
                new Country {Active = true, Name = "Mali", Code = "223", ISOAlpha2 = "ML", ISOAlpha3 = "MLI"},
                new Country {Active = true, Name = "Malta", Code = "356", ISOAlpha2 = "MT", ISOAlpha3 = "MLT"},
                new Country {Active = true, Name = "Marshall Islands", Code = "692", ISOAlpha2 = "MH", ISOAlpha3 = "MHL"},
                new Country {Active = true, Name = "Mauritania", Code = "222", ISOAlpha2 = "MR", ISOAlpha3 = "MRT"},
                new Country {Active = true, Name = "Mauritius", Code = "230", ISOAlpha2 = "MU", ISOAlpha3 = "MUS"},
                new Country {Active = true, Name = "Mayotte", Code = "262", ISOAlpha2 = "YT", ISOAlpha3 = "MYT"},
                new Country {Active = true, Name = "Mexico", Code = "52", ISOAlpha2 = "MX", ISOAlpha3 = "MEX"},
                new Country {Active = true, Name = "Micronesia", Code = "691", ISOAlpha2 = "FM", ISOAlpha3 = "FSM"},
                new Country {Active = true, Name = "Moldova", Code = "373", ISOAlpha2 = "MD", ISOAlpha3 = "MDA"},
                new Country {Active = true, Name = "Monaco", Code = "377", ISOAlpha2 = "MC", ISOAlpha3 = "MCO"},
                new Country {Active = true, Name = "Mongolia", Code = "976", ISOAlpha2 = "MN", ISOAlpha3 = "MNG"},
                new Country {Active = true, Name = "Montenegro", Code = "382", ISOAlpha2 = "ME", ISOAlpha3 = "MNE"},
                new Country {Active = true, Name = "Montserrat", Code = "1-664", ISOAlpha2 = "MS", ISOAlpha3 = "MSR"},
                new Country {Active = true, Name = "Morocco", Code = "212", ISOAlpha2 = "MA", ISOAlpha3 = "MAR"},
                new Country {Active = true, Name = "Mozambique", Code = "258", ISOAlpha2 = "MZ", ISOAlpha3 = "MOZ"},
                new Country {Active = true, Name = "Myanmar", Code = "95", ISOAlpha2 = "MM", ISOAlpha3 = "MMR"},
                new Country {Active = true, Name = "Namibia", Code = "264", ISOAlpha2 = "NA", ISOAlpha3 = "NAM"},
                new Country {Active = true, Name = "Nauru", Code = "674", ISOAlpha2 = "NR", ISOAlpha3 = "NRU"},
                new Country {Active = true, Name = "Nepal", Code = "977", ISOAlpha2 = "NP", ISOAlpha3 = "NPL"},
                new Country {Active = true, Name = "Netherlands", Code = "31", ISOAlpha2 = "NL", ISOAlpha3 = "NLD"},
                new Country {Active = true, Name = "Netherlands Antilles", Code = "599", ISOAlpha2 = "AN", ISOAlpha3 = "ANT"},
                new Country {Active = true, Name = "New Caledonia", Code = "687", ISOAlpha2 = "NC", ISOAlpha3 = "NCL"},
                new Country {Active = true, Name = "New Zealand", Code = "64", ISOAlpha2 = "NZ", ISOAlpha3 = "NZL"},
                new Country {Active = true, Name = "Nicaragua", Code = "505", ISOAlpha2 = "NI", ISOAlpha3 = "NIC"},
                new Country {Active = true, Name = "Niger", Code = "227", ISOAlpha2 = "NE", ISOAlpha3 = "NER"},
                new Country {Active = true, Name = "Nigeria", Code = "234", ISOAlpha2 = "NG", ISOAlpha3 = "NGA"},
                new Country {Active = true, Name = "Niue", Code = "683", ISOAlpha2 = "NU", ISOAlpha3 = "NIU"},
                new Country {Active = true, Name = "North Korea", Code = "850", ISOAlpha2 = "KP", ISOAlpha3 = "PRK"},
                new Country {Active = true, Name = "Northern Mariana Islands", Code = "1-670", ISOAlpha2 = "MP", ISOAlpha3 = "MNP"},
                new Country {Active = true, Name = "Norway", Code = "47", ISOAlpha2 = "NO", ISOAlpha3 = "NOR"},
                new Country {Active = true, Name = "Oman", Code = "968", ISOAlpha2 = "OM", ISOAlpha3 = "OMN"},
                new Country {Active = true, Name = "Pakistan", Code = "92", ISOAlpha2 = "PK", ISOAlpha3 = "PAK"},
                new Country {Active = true, Name = "Palau", Code = "680", ISOAlpha2 = "PW", ISOAlpha3 = "PLW"},
                new Country {Active = true, Name = "Palestine", Code = "970", ISOAlpha2 = "PS", ISOAlpha3 = "PSE"},
                new Country {Active = true, Name = "Panama", Code = "507", ISOAlpha2 = "PA", ISOAlpha3 = "PAN"},
                new Country {Active = true, Name = "Papua New Guinea", Code = "675", ISOAlpha2 = "PG", ISOAlpha3 = "PNG"},
                new Country {Active = true, Name = "Paraguay", Code = "595", ISOAlpha2 = "PY", ISOAlpha3 = "PRY"},
                new Country {Active = true, Name = "Peru", Code = "51", ISOAlpha2 = "PE", ISOAlpha3 = "PER"},
                new Country {Active = true, Name = "Philippines", Code = "63", ISOAlpha2 = "PH", ISOAlpha3 = "PHL"},
                new Country {Active = true, Name = "Pitcairn", Code = "64", ISOAlpha2 = "PN", ISOAlpha3 = "PCN"},
                new Country {Active = true, Name = "Poland", Code = "48", ISOAlpha2 = "PL", ISOAlpha3 = "POL"},
                new Country {Active = true, Name = "Portugal", Code = "351", ISOAlpha2 = "PT", ISOAlpha3 = "PRT"},
                new Country {Active = true, Name = "Puerto Rico", Code = "1-787, 1-939", ISOAlpha2 = "PR", ISOAlpha3 = "PRI"},
                new Country {Active = true, Name = "Qatar", Code = "974", ISOAlpha2 = "QA", ISOAlpha3 = "QAT"},
                new Country {Active = true, Name = "Republic of the Congo", Code = "242", ISOAlpha2 = "CG", ISOAlpha3 = "COG"},
                new Country {Active = true, Name = "Reunion", Code = "262", ISOAlpha2 = "RE", ISOAlpha3 = "REU"},
                new Country {Active = true, Name = "Romania", Code = "40", ISOAlpha2 = "RO", ISOAlpha3 = "ROU"},
                new Country {Active = true, Name = "Russia", Code = "7", ISOAlpha2 = "RU", ISOAlpha3 = "RUS"},
                new Country {Active = true, Name = "Rwanda", Code = "250", ISOAlpha2 = "RW", ISOAlpha3 = "RWA"},
                new Country {Active = true, Name = "Saint Barthelemy", Code = "590", ISOAlpha2 = "BL", ISOAlpha3 = "BLM"},
                new Country {Active = true, Name = "Saint Helena", Code = "290", ISOAlpha2 = "SH", ISOAlpha3 = "SHN"},
                new Country {Active = true, Name = "Saint Kitts and Nevis", Code = "1-869", ISOAlpha2 = "KN", ISOAlpha3 = "KNA"},
                new Country {Active = true, Name = "Saint Lucia", Code = "1-758", ISOAlpha2 = "LC", ISOAlpha3 = "LCA"},
                new Country {Active = true, Name = "Saint Martin", Code = "590", ISOAlpha2 = "MF", ISOAlpha3 = "MAF"},
                new Country {Active = true, Name = "Saint Pierre and Miquelon", Code = "508", ISOAlpha2 = "PM", ISOAlpha3 = "SPM"},
                new Country {Active = true, Name = "Saint Vincent and the Grenadines", Code = "1-784", ISOAlpha2 = "VC", ISOAlpha3 = "VCT"},
                new Country {Active = true, Name = "Samoa", Code = "685", ISOAlpha2 = "WS", ISOAlpha3 = "WSM"},
                new Country {Active = true, Name = "San Marino", Code = "378", ISOAlpha2 = "SM", ISOAlpha3 = "SMR"},
                new Country {Active = true, Name = "Sao Tome and Principe", Code = "239", ISOAlpha2 = "ST", ISOAlpha3 = "STP"},
                new Country {Active = true, Name = "Saudi Arabia", Code = "966", ISOAlpha2 = "SA", ISOAlpha3 = "SAU"},
                new Country {Active = true, Name = "Senegal", Code = "221", ISOAlpha2 = "SN", ISOAlpha3 = "SEN"},
                new Country {Active = true, Name = "Serbia", Code = "381", ISOAlpha2 = "RS", ISOAlpha3 = "SRB"},
                new Country {Active = true, Name = "Seychelles", Code = "248", ISOAlpha2 = "SC", ISOAlpha3 = "SYC"},
                new Country {Active = true, Name = "Sierra Leone", Code = "232", ISOAlpha2 = "SL", ISOAlpha3 = "SLE"},
                new Country {Active = true, Name = "Singapore", Code = "65", ISOAlpha2 = "SG", ISOAlpha3 = "SGP"},
                new Country {Active = true, Name = "Sint Maarten", Code = "1-721", ISOAlpha2 = "SX", ISOAlpha3 = "SXM"},
                new Country {Active = true, Name = "Slovakia", Code = "421", ISOAlpha2 = "SK", ISOAlpha3 = "SVK"},
                new Country {Active = true, Name = "Slovenia", Code = "386", ISOAlpha2 = "SI", ISOAlpha3 = "SVN"},
                new Country {Active = true, Name = "Solomon Islands", Code = "677", ISOAlpha2 = "SB", ISOAlpha3 = "SLB"},
                new Country {Active = true, Name = "Somalia", Code = "252", ISOAlpha2 = "SO", ISOAlpha3 = "SOM"},
                new Country {Active = true, Name = "South Africa", Code = "27", ISOAlpha2 = "ZA", ISOAlpha3 = "ZAF"},
                new Country {Active = true, Name = "South Korea", Code = "82", ISOAlpha2 = "KR", ISOAlpha3 = "KOR"},
                new Country {Active = true, Name = "South Sudan", Code = "211", ISOAlpha2 = "SS", ISOAlpha3 = "SSD"},
                new Country {Active = true, Name = "Spain", Code = "34", ISOAlpha2 = "ES", ISOAlpha3 = "ESP"},
                new Country {Active = true, Name = "Sri Lanka", Code = "94", ISOAlpha2 = "LK", ISOAlpha3 = "LKA"},
                new Country {Active = true, Name = "Sudan", Code = "249", ISOAlpha2 = "SD", ISOAlpha3 = "SDN"},
                new Country {Active = true, Name = "Suriname", Code = "597", ISOAlpha2 = "SR", ISOAlpha3 = "SUR"},
                new Country {Active = true, Name = "Svalbard and Jan Mayen", Code = "47", ISOAlpha2 = "SJ", ISOAlpha3 = "SJM"},
                new Country {Active = true, Name = "Swaziland", Code = "268", ISOAlpha2 = "SZ", ISOAlpha3 = "SWZ"},
                new Country {Active = true, Name = "Sweden", Code = "46", ISOAlpha2 = "SE", ISOAlpha3 = "SWE"},
                new Country {Active = true, Name = "Switzerland", Code = "41", ISOAlpha2 = "CH", ISOAlpha3 = "CHE"},
                new Country {Active = true, Name = "Syria", Code = "963", ISOAlpha2 = "SY", ISOAlpha3 = "SYR"},
                new Country {Active = true, Name = "Taiwan", Code = "886", ISOAlpha2 = "TW", ISOAlpha3 = "TWN"},
                new Country {Active = true, Name = "Tajikistan", Code = "992", ISOAlpha2 = "TJ", ISOAlpha3 = "TJK"},
                new Country {Active = true, Name = "Tanzania", Code = "255", ISOAlpha2 = "TZ", ISOAlpha3 = "TZA"},
                new Country {Active = true, Name = "Thailand", Code = "66", ISOAlpha2 = "TH", ISOAlpha3 = "THA"},
                new Country {Active = true, Name = "Togo", Code = "228", ISOAlpha2 = "TG", ISOAlpha3 = "TGO"},
                new Country {Active = true, Name = "Tokelau", Code = "690", ISOAlpha2 = "TK", ISOAlpha3 = "TKL"},
                new Country {Active = true, Name = "Tonga", Code = "676", ISOAlpha2 = "TO", ISOAlpha3 = "TON"},
                new Country {Active = true, Name = "Trinidad and Tobago", Code = "1-868", ISOAlpha2 = "TT", ISOAlpha3 = "TTO"},
                new Country {Active = true, Name = "Tunisia", Code = "216", ISOAlpha2 = "TN", ISOAlpha3 = "TUN"},
                new Country {Active = true, Name = "Turkey", Code = "90", ISOAlpha2 = "TR", ISOAlpha3 = "TUR"},
                new Country {Active = true, Name = "Turkmenistan", Code = "993", ISOAlpha2 = "TM", ISOAlpha3 = "TKM"},
                new Country {Active = true, Name = "Turks and Caicos Islands", Code = "1-649", ISOAlpha2 = "TC", ISOAlpha3 = "TCA"},
                new Country {Active = true, Name = "Tuvalu", Code = "688", ISOAlpha2 = "TV", ISOAlpha3 = "TUV"},
                new Country {Active = true, Name = "U.S. Virgin Islands", Code = "1-340", ISOAlpha2 = "VI", ISOAlpha3 = "VIR"},
                new Country {Active = true, Name = "Uganda", Code = "256", ISOAlpha2 = "UG", ISOAlpha3 = "UGA"},
                new Country {Active = true, Name = "Ukraine", Code = "380", ISOAlpha2 = "UA", ISOAlpha3 = "UKR"},
                new Country {Active = true, Name = "United Arab Emirates", Code = "971", ISOAlpha2 = "AE", ISOAlpha3 = "ARE"},
                new Country {Active = true, Name = "United Kingdom", Code = "44", ISOAlpha2 = "GB", ISOAlpha3 = "GBR"},
                new Country {Active = true, Name = "United States", Code = "1", ISOAlpha2 = "US", ISOAlpha3 = "USA"},
                new Country {Active = true, Name = "Uruguay", Code = "598", ISOAlpha2 = "UY", ISOAlpha3 = "URY"},
                new Country {Active = true, Name = "Uzbekistan", Code = "998", ISOAlpha2 = "UZ", ISOAlpha3 = "UZB"},
                new Country {Active = true, Name = "Vanuatu", Code = "678", ISOAlpha2 = "VU", ISOAlpha3 = "VUT"},
                new Country {Active = true, Name = "Vatican", Code = "379", ISOAlpha2 = "VA", ISOAlpha3 = "VAT"},
                new Country {Active = true, Name = "Venezuela", Code = "58", ISOAlpha2 = "VE", ISOAlpha3 = "VEN"},
                new Country {Active = true, Name = "Vietnam", Code = "84", ISOAlpha2 = "VN", ISOAlpha3 = "VNM"},
                new Country {Active = true, Name = "Wallis and Futuna", Code = "681", ISOAlpha2 = "WF", ISOAlpha3 = "WLF"},
                new Country {Active = true, Name = "Western Sahara", Code = "212", ISOAlpha2 = "EH", ISOAlpha3 = "ESH"},
                new Country {Active = true, Name = "Yemen", Code = "967", ISOAlpha2 = "YE", ISOAlpha3 = "YEM"},
                new Country {Active = true, Name = "Zambia", Code = "260", ISOAlpha2 = "ZM", ISOAlpha3 = "ZMB"},
                new Country {Active = true, Name = "Zimbabwe", Code = "263", ISOAlpha2 = "ZW", ISOAlpha3 = "ZWE"}
            };

            return allCountries;
        }
    }
}