using System.Linq;
using Core.Model.Enums;

namespace Core.Model
{
    public partial class DefaultDataDbInitializer
    {
        private MediaSource[] MediaSourcesRadioStations(HemsamaritenWindowsServiceDbContext context)
        {
            var SE = context.Countries.Where(c => c.Active && c.ISOAlpha2 == "SE").Select(c => c).FirstOrDefault();
            var NO = context.Countries.Where(c => c.Active && c.ISOAlpha2 == "NO").Select(c => c).FirstOrDefault();
            var DK = context.Countries.Where(c => c.Active && c.ISOAlpha2 == "DK").Select(c => c).FirstOrDefault();
            var GB = context.Countries.Where(c => c.Active && c.ISOAlpha2 == "GB").Select(c => c).FirstOrDefault();

            var mediaSources = new MediaSource[]
            {
                new MediaSource { Active=true, Name="SR P1", Url = "http://sverigesradio.se/topsy/direkt/132-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P2", Url = "http://sverigesradio.se/topsy/direkt/2562-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P3", Url = "http://sverigesradio.se/topsy/direkt/164-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Ekot sänder direkt", Url = "http://sverigesradio.se/topsy/direkt/4540-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Plus", Url = "http://sverigesradio.se/topsy/direkt/4951-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Blekinge", Url = "http://sverigesradio.se/topsy/direkt/213-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Dalarna", Url = "http://sverigesradio.se/topsy/direkt/223-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Gotland", Url = "http://sverigesradio.se/topsy/direkt/205-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Gävleborg", Url = "http://sverigesradio.se/topsy/direkt/210-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Göteborg", Url = "http://sverigesradio.se/topsy/direkt/212-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Halland", Url = "http://sverigesradio.se/topsy/direkt/220-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Jämtland", Url = "http://sverigesradio.se/topsy/direkt/200-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Jönköping", Url = "http://sverigesradio.se/topsy/direkt/203-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Kalmar", Url = "http://sverigesradio.se/topsy/direkt/201-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Kristianstad", Url = "http://sverigesradio.se/topsy/direkt/211-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Kronoberg", Url = "http://sverigesradio.se/topsy/direkt/214-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Malmöhus", Url = "http://sverigesradio.se/topsy/direkt/207-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Norrbotten", Url = "http://sverigesradio.se/topsy/direkt/209-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Sjuhärad", Url = "http://sverigesradio.se/topsy/direkt/206-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Skaraborg", Url = "http://sverigesradio.se/topsy/direkt/208-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Stockholm", Url = "http://sverigesradio.se/topsy/direkt/701-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Sörmland", Url = "http://sverigesradio.se/topsy/direkt/202-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Uppland", Url = "http://sverigesradio.se/topsy/direkt/218-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Värmland", Url = "http://sverigesradio.se/topsy/direkt/204-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Väst", Url = "http://sverigesradio.se/topsy/direkt/219-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Västerbotten", Url = "http://sverigesradio.se/topsy/direkt/215-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Västernorrland", Url = "http://sverigesradio.se/topsy/direkt/216-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Västmanland", Url = "http://sverigesradio.se/topsy/direkt/217-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Örebro", Url = "http://sverigesradio.se/topsy/direkt/221-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Östergötland", Url = "http://sverigesradio.se/topsy/direkt/222-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P3 Din gata", Url = "http://sverigesradio.se/topsy/direkt/2576-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P5 Sthlm", Url = "http://sverigesradio.se/topsy/direkt/2842-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P2 Språk och musik", Url = "http://sverigesradio.se/topsy/direkt/163-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P6", Url = "http://sverigesradio.se/topsy/direkt/166-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P3 Star", Url = "http://sverigesradio.se/topsy/direkt/1607-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Radioapans knattekanal", Url = "http://sverigesradio.se/topsy/direkt/2755-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P2 Klassiskt", Url = "http://sverigesradio.se/topsy/direkt/1603-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Sápmi", Url = "http://sverigesradio.se/topsy/direkt/224-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Sisuradio", Url = "http://sverigesradio.se/topsy/direkt/226-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P2 Världen", Url = "http://sverigesradio.se/topsy/direkt/2619-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Extra 01", Url = "http://sverigesradio.se/topsy/direkt/2383-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Extra 02", Url = "http://sverigesradio.se/topsy/direkt/2384-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Extra 03", Url = "http://sverigesradio.se/topsy/direkt/2385-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Extra 04", Url = "http://sverigesradio.se/topsy/direkt/2386-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Extra 05", Url = "http://sverigesradio.se/topsy/direkt/2387-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Extra 06", Url = "http://sverigesradio.se/topsy/direkt/2388-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Extra 07", Url = "http://sverigesradio.se/topsy/direkt/2389-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Extra 08", Url = "http://sverigesradio.se/topsy/direkt/2390-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Extra 09", Url = "http://sverigesradio.se/topsy/direkt/3268-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR Extra 10", Url = "http://sverigesradio.se/topsy/direkt/3269-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P2 Klassisk Jul", Url = "http://sverigesradio.se/topsy/direkt/3036-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="SR P4 Bjällerklang", Url = "http://sverigesradio.se/topsy/direkt/3034-hi-aac.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},

                new MediaSource { Active=true, Name="Malmökanalen", Url =  "http://stream.nsp.se:8000/MNR89_MP3_Lo", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="Radio Malmökanalen", Url =  "http://stream.nsp.se:8000/MNR90_MP3_Lo", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},
                new MediaSource { Active=true, Name="Radio AF", Url =  "http://live.radioaf.se:8000/;stream/1", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = SE},

                new MediaSource { Active=true, Name="DR P1", Url =  "http://live-icy.gss.dr.dk/A/A03H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P2", Url =  "http://live-icy.gss.dr.dk/A/A04H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P3", Url =  "http://live-icy.gss.dr.dk/A/A05H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P4 Bornholm", Url =  "http://live-icy.gss.dr.dk/A/A06H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P4 Esbjerg", Url =  "http://live-icy.gss.dr.dk/A/A15H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P4 Fyn", Url =  "http://live-icy.gss.dr.dk/A/A07H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P4 København", Url =  "http://live-icy.gss.dr.dk/A/A08H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P4 Midt & Vest", Url =  "http://live-icy.gss.dr.dk/A/A09H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P4 Nordjylland", Url =  "http://live-icy.gss.dr.dk/A/A10H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P4 Sjælland", Url =  "http://live-icy.gss.dr.dk/A/A11H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P4 Syd", Url =  "http://live-icy.gss.dr.dk/A/A12H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P4 Trekanten", Url =  "http://live-icy.gss.dr.dk/A/A13H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P4 Østjyllands Radio", Url =  "http://live-icy.gss.dr.dk/A/A14H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P5", Url =  "http://live-icy.gss.dr.dk/A/A25L.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},
                new MediaSource { Active=true, Name="DR P6 BEAT", Url =  "http://live-icy.gss.dr.dk/A/A29H.mp3.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = DK},

                new MediaSource { Active=true, Name="NRK P1", Url = "http://lyd.nrk.no/nrk_radio_p1_ostlandssendingen_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Buskerud", Url = "http://lyd.nrk.no/nrk_radio_p1_buskerud_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Finnmark", Url = "http://lyd.nrk.no/nrk_radio_p1_finnmark_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Hedmark og Oppland", Url = "http://lyd.nrk.no/nrk_radio_p1_hedmark_og_oppland_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Hordaland", Url = "http://lyd.nrk.no/nrk_radio_p1_hordaland_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Møre og Romsdal", Url = "http://lyd.nrk.no/nrk_radio_p1_more_og_romsdal_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Nordland", Url = "http://lyd.nrk.no/nrk_radio_p1_nordland_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Rogaland", Url = "http://lyd.nrk.no/nrk_radio_p1_rogaland_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Sogn og Fjordane", Url = "http://lyd.nrk.no/nrk_radio_p1_sogn_og_fjordane_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Sogn og Fjordane MP3 (høy)", Url = "http://lyd.nrk.no/nrk_radio_p1_sogn_og_fjordane_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Sørlandet", Url = "http://lyd.nrk.no/nrk_radio_p1_sorlandet_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Telemark", Url = "http://lyd.nrk.no/nrk_radio_p1_telemark_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Troms", Url = "http://lyd.nrk.no/nrk_radio_p1_troms_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Trøndelag", Url = "http://lyd.nrk.no/nrk_radio_p1_trondelag_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Vestfold", Url = "http://lyd.nrk.no/nrk_radio_p1_vestfold_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Østfold", Url = "http://lyd.nrk.no/nrk_radio_p1_ostfold_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1 Østlandssendingen", Url = "http://lyd.nrk.no/nrk_radio_p1_ostlandssendingen_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P2", Url = "http://lyd.nrk.no/nrk_radio_p2_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P3", Url = "http://lyd.nrk.no/nrk_radio_p3_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P1+", Url = "http://lyd.nrk.no/nrk_radio_p1pluss_mp3_h.m3u", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P13", Url = "http://lyd.nrk.no/nrk_radio_p13_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK mP3", Url = "http://lyd.nrk.no/nrk_radio_mp3_aac_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK Super", Url = "http://lyd.nrk.no/nrk_radio_super_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK Alltid nyheter", Url = "http://lyd.nrk.no/nrk_radio_alltid_nyheter_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK P3 Urørt", Url = "http://lyd.nrk.no/nrk_radio_p3_urort_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK Sport", Url = "http://lyd.nrk.no/nrk_radio_sport_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK Sápmi radio", Url = "http://lyd.nrk.no/nrk_radio_sami_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK Klassisk", Url = "http://lyd.nrk.no/nrk_radio_klassisk_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK Jazz", Url = "http://lyd.nrk.no/nrk_radio_jazz_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},
                new MediaSource { Active=true, Name="NRK Folkemusikk", Url = "http://lyd.nrk.no/nrk_radio_folkemusikk_mp3_h", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = NO},

                new MediaSource { Active=true, Name="BBC Radio 1 (Nationella stationer)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio 1xtra (Nationella stationer)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1xtra_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio 2 (Nationella stationer)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio 3 (Nationella stationer)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio3_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio 4FM (Nationella stationer)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4fm_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio 4LW (Nationella stationer)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4lw_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio 4 Extra (Nationella stationer)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4extra_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio 5 Live (Nationella stationer)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio5live_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio 5 Live Sportsball Extra", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio5extra_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio 6 Music (Nationella stationer)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_6music_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Asian Network (Nationella stationer)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_asianet_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC World Service UK stream (Nationella stationer)", Url = "http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-eieuk", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC World Service News stream (Nationella stationer)", Url = "http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-einws", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Cymru (Nationer och regioner)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_cymru_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Foyle (Nationer och regioner)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_foyle_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio nan Gàidheal (Nationer och regioner)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_nangaidheal_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Scotland (Nationer och regioner)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_scotlandfm_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Ulster (Nationer och regioner)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_ulster_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Wales (Nationer och regioner)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_walesmw_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Berkshire (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrberk_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Bristol (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrbris_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Cambridgeshire (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrcambs_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Cornwall (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrcorn_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Coventry & Warwickshire (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrwmcandw_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Cumbria (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrcumbria_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Derby (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrderby_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Devon (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrdevon_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Essex (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lressex_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Gloucestershire (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrgloucs_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Guernsey (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrguern_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Hereford & Worcester (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrhandw_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Humberside (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrhumber_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Jersey (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrjersey_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Kent (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrkent_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Lancashire (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrlancs_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Leeds (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrleeds_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Leicester (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrleics_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Lincolnshire (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrlincs_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio London (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrldn_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Manchester (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrmanc_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Merseyside (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrmersey_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Newcastle (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrnewc_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Norfolk (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrnorfolk_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Northampton (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrnthhnts_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Nottingham (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrnotts_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Oxford (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lroxford_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Sheffield (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrsheff_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Shropshire (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrshrops_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Solent (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrsolent_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Somerset (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrsomer_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Stoke (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrsomer_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio Suffolk (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrsuffolk_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Surrey (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrsurrey_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Sussex (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrsussex_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Tees (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrtees_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Three Counties Radio (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lr3cr_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Wiltshire (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrwilts_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC WM 95.6 (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrwm_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB},
                new MediaSource { Active=true, Name="BBC Radio York (Lokalradio)", Url = "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lryork_mf_p", MediaCategoryType = MediaCategoryType.InternetStreamRadio, MediaCountry = GB}
            };
            return mediaSources;
        }
    }
}